# Flutter脚手架代码分析配置
# 使用very_good_analysis作为基础，这是业界最严格的Flutter代码规范
# 更多信息: https://dart.dev/guides/language/analysis-options

include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # 自定义规则，根据项目需要调整
    file_names: true
    always_use_package_imports: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
    
    # 禁用一些在开发阶段可能过于严格的规则
    public_member_api_docs: false  # 开发阶段不强制要求所有公共成员都有文档
    
analyzer:
  exclude:
    - "**/*.g.dart"      # 排除代码生成文件
    - "**/*.freezed.dart" # 排除freezed生成文件
    - "build/**"         # 排除构建输出
    - "ios/**"          # 排除iOS原生代码
    - "android/**"      # 排除Android原生代码
    - "linux/**"        # 排除Linux原生代码
    - "macos/**"        # 排除macOS原生代码
    - "windows/**"      # 排除Windows原生代码
    - "web/**"          # 排除Web原生代码
    
  errors:
    # 将某些警告提升为错误，确保代码质量
    invalid_annotation_target: error
    missing_required_param: error
    missing_return: error 